name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.0.2
  liquid_pull_to_refresh: ^3.0.1
  cupertino_icons: ^1.0.2
  easy_stepper: ^0.1.2
  flutter_custom_clippers: ^2.0.0
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  icons_plus: ^2.0.1
  liquid_swipe: ^3.0.0
  lottie: ^1.4.3
  salomon_bottom_bar: ^3.3.1
  spring_button: ^2.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  either_dart: ^0.2.0
  dartz: ^0.10.1
  percent_indicator: ^4.2.2
  audioplayers: ^1.1.1
  confetti: ^0.7.0
  flip_card: ^0.6.0
  flutter_zoom_drawer: ^3.0.3
  like_button: ^2.0.5
  dropdown_button2: ^1.9.2
  intl: ^0.18.0
  url_launcher: ^6.1.7
  string_similarity: ^2.0.0
  speech_to_text: ^6.1.1
 
  flutter_tts: ^3.6.3
  translator: ^0.1.7
  clipboard: ^0.1.3
  avatar_glow: ^2.0.2
  substring_highlight: ^1.0.33


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - levelicon/
    - Lelottie/
    - assets/
    - lot/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  #create by :khaled barakat
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairo/static/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
